### ISSUE TITLE
qBOP will not update OPNSense after 24.7 upgrade

### ISSUE THREAD

**Issue by Saber1998** [clajiness/qbop#1]
After upgrading to OPNsense 24.7 qBOP will not update the alias. This is the error I see in the qBOP logs:

# Logfile created on 2024-07-25 11:41:06 -0400 by logger.rb/v1.4.3
I, [2024-07-25T11:41:06.292041 #1707]  INFO -- : starting qBop v0.2.0
I, [2024-07-25T11:41:06.292236 #1707]  INFO -- : config.yml file found successfully
I, [2024-07-25T11:41:06.292258 #1707]  INFO -- : ----------
I, [2024-07-25T11:41:06.292272 #1707]  INFO -- : start of loop
I, [2024-07-25T11:41:06.488328 #1707]  INFO -- : Proton returned the forwarded port: 58432
I, [2024-07-25T11:41:06.712662 #1707]  INFO -- : OPNsense port 59425 does not match Proton forwarded port 58432. Attempt 1 of 3.
I, [2024-07-25T11:41:06.715582 #1707]  INFO -- : qBit port 58432 matches Proton forwarded port 58432
I, [2024-07-25T11:41:06.715654 #1707]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-25T11:41:06.715674 #1707]  INFO -- : ----------
I, [2024-07-25T11:41:51.759130 #1707]  INFO -- : start of loop
I, [2024-07-25T11:41:51.960354 #1707]  INFO -- : Proton returned the forwarded port: 58432
I, [2024-07-25T11:41:52.188250 #1707]  INFO -- : OPNsense port 59425 does not match Proton forwarded port 58432. Attempt 2 of 3.
I, [2024-07-25T11:41:52.190980 #1707]  INFO -- : qBit port 58432 matches Proton forwarded port 58432
I, [2024-07-25T11:41:52.191077 #1707]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-25T11:41:52.191103 #1707]  INFO -- : ----------

I ended up updating the port manually and it worked. I'm suspecting there was a change in the API after the upgrade.

**Comment by clajiness** [comment]
Thank you for the heads up. I'll check it out when I upgrade to 24.7. I'm likely not going to upgrade until the .1 release, so my apologies for not getting on this sooner. I'll update here when I sort it out. 👍

**Comment by Saber1998** [comment]
> Any chance the 24.7_5 hotfix remedies the issue?
> 
> 'mvc: fix API regression due to getParams() removal'

Looks like the OPNsense update did fix it :)

# Logfile created on 2024-07-26 08:35:00 -0400 by logger.rb/v1.4.3
I, [2024-07-26T08:35:00.745880 #11067]  INFO -- : starting qBop v0.2.0
I, [2024-07-26T08:35:00.756569 #11067]  INFO -- : config.yml file found successfully
I, [2024-07-26T08:35:00.756606 #11067]  INFO -- : ----------
I, [2024-07-26T08:35:00.756623 #11067]  INFO -- : start of loop
I, [2024-07-26T08:35:00.956183 #11067]  INFO -- : Proton returned the forwarded port: 42876
I, [2024-07-26T08:35:01.351669 #11067]  INFO -- : OPNsense port 58432 does not match Proton forwarded port 42876. Attempt 1 of 3.
I, [2024-07-26T08:35:01.354343 #11067]  INFO -- : qBit port 58432 does not match Proton forwarded port 42876. Attempt 1 of 3.
I, [2024-07-26T08:35:01.354401 #11067]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-26T08:35:01.354415 #11067]  INFO -- : ----------
I, [2024-07-26T08:35:46.399533 #11067]  INFO -- : start of loop
I, [2024-07-26T08:35:46.765692 #11067]  INFO -- : Proton returned the forwarded port: 42876
I, [2024-07-26T08:35:46.987672 #11067]  INFO -- : OPNsense port 58432 does not match Proton forwarded port 42876. Attempt 2 of 3.
I, [2024-07-26T08:35:46.990947 #11067]  INFO -- : qBit port 58432 does not match Proton forwarded port 42876. Attempt 2 of 3.
I, [2024-07-26T08:35:46.991062 #11067]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-26T08:35:46.991095 #11067]  INFO -- : ----------
I, [2024-07-26T08:36:32.036177 #11067]  INFO -- : start of loop
I, [2024-07-26T08:36:32.233316 #11067]  INFO -- : Proton returned the forwarded port: 42876
I, [2024-07-26T08:36:32.453993 #11067]  INFO -- : OPNsense port 58432 does not match Proton forwarded port 42876. Attempt 3 of 3.
I, [2024-07-26T08:36:32.582057 #11067]  INFO -- : OPNsense alias has been updated to 42876
I, [2024-07-26T08:36:34.748369 #11067]  INFO -- : OPNsense alias applied successfully
I, [2024-07-26T08:36:34.750996 #11067]  INFO -- : qBit port 58432 does not match Proton forwarded port 42876. Attempt 3 of 3.
I, [2024-07-26T08:36:35.153108 #11067]  INFO -- : qBit's port has been updated to 42876
I, [2024-07-26T08:36:35.153191 #11067]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-26T08:36:35.153218 #11067]  INFO -- : ----------
I, [2024-07-26T08:37:20.183107 #11067]  INFO -- : start of loop
I, [2024-07-26T08:37:20.380304 #11067]  INFO -- : Proton returned the forwarded port: 42876
I, [2024-07-26T08:37:20.611179 #11067]  INFO -- : OPNsense port 42876 matches Proton forwarded port 42876
I, [2024-07-26T08:37:20.614433 #11067]  INFO -- : qBit port 42876 matches Proton forwarded port 42876
I, [2024-07-26T08:37:20.614518 #11067]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-07-26T08:37:20.614546 #11067]  INFO -- : ----------

**Comment by clajiness** [comment]
Awesome! Glad to hear it. Thanks for the report, though!
