### ISSUE TITLE
Running on Synology Docker - No Qbittorrent

### ISSUE THREAD

**Issue by alexjn1984** [clajiness/qbop#4]
Hey there,

I'm trying to run this in container manager on a Synology. I have a separate setup with docker network with my qbit and glutun, so this would just be for the host, and OPNSense.

Running in container manager, nothing shows up in the log section, nor does adding a /log mapping produce a file. Are the qbit settings required for it to run properly? Is it possible to run it only for OPNSense onfig, instead of both?

Any help would be appreciated, and if there is a tip jar I can contribute some.

**Comment by clajiness** [comment]
hello,

ya, it's gonna break without the qbit settings. i'll be home tomorrow and should have a few minutes to make qbit optional. i'll let you know when it's tested and ready.

appreciate the offer for a tip, but it's not necessary. 👍

**Comment by clajiness** [comment]
hi!

you should able to pull v0.5.1 and use `QBIT_SKIP=true` in your compose file to ignore qBit altogether. it seems to be working fine on my instance, but let me know if you run into any problems.

**Comment by clajiness** [comment]
morning,

i did a little more testing this morning and found a little logic bug. it should be good to go now with v0.5.2. 👍

i'm gonna close this as it works fine, but feel free to open another if you have trouble getting it running.

**Comment by alexjn1984** [comment]
Thank you very much, I figured out why my logging wasn't working either, but fixed that, and now I think its just a config issue between the synology docker container and the router. I'll post when I resolve it.

**Comment by clajiness** [comment]
What are the logs saying?

**Comment by alexjn1984** [comment]
I, [2024-12-04T02:46:54.809350 #1]  INFO -- : start of loop
E, [2024-12-04T02:46:56.673095 #1] ERROR -- : Proton didn't return a forwarded port. Sleeping for 45 seconds and trying again.

I do know from the Synology I can ping the router, but I can't ping the proton gateway

**Comment by alexjn1984** [comment]
Progress
figured out the FW rule that was blocking. Now getting port, but some additional errors:
I, [2024-12-04T03:12:53.970201 #1]  INFO -- : Proton returned the forwarded port: 46381
E, [2024-12-04T03:12:53.970496 #1] ERROR -- : OPNsense has returned an error:
E, [2024-12-04T03:12:53.970539 #1] ERROR -- : not an HTTP URI (ArgumentError)
/usr/local/lib/ruby/3.3.0/net/http/generic_request.rb:21:in `initialize'
/usr/local/lib/ruby/3.3.0/net/http/request.rb:83:in `initialize'
/opt/qbop/service/opnsense.rb:12:in `new'
/opt/qbop/service/opnsense.rb:12:in `get_alias_uuid'
/opt/qbop/qbop.rb:96:in `block in <main>'
<internal:kernel>:187:in `loop'
/opt/qbop/qbop.rb:59:in `<main>'
I, [2024-12-04T03:12:53.970604 #1]  INFO -- : sleeping for 45 seconds and trying again

**Comment by clajiness** [comment]
Can you post your redacted compose file?

**Comment by alexjn1984** [comment]
![Screenshot 2024-12-04 at 22 00 32](https://github.com/user-attachments/assets/1a585ef3-f1be-4179-8424-31233e10b4b4)
So I build it through container manager. I can do a compose command, but its going to have the same information as is on display here.

Esentially I just input environment variables 1-7

**Comment by clajiness** [comment]
That looks fine, but what's the OPNsense interface address? That may be our problem.

**Comment by alexjn1984** [comment]
It's the router address (192.168.x.x)

Sent from Proton Mail Android

-------- Original Message --------

**Comment by clajiness** [comment]
Sorry, I should've been more specific. That value needs to be prepended with http(s). For example, `https://192.168.x.x`. I just wanted to make sure it is.

Also, I'm gonna reopen this. It's annoying to have to look at closed issues.

**Comment by alexjn1984** [comment]
Will test it tonight

Sent from Proton Mail Android

-------- Original Message --------

**Comment by alexjn1984** [comment]
Success! Thank you for all the help!

I, [2024-12-06T02:54:56.776223 #1]  INFO -- : start of loop
I, [2024-12-06T02:54:56.872266 #1]  INFO -- : Proton returned the forwarded port: 46381
I, [2024-12-06T02:54:57.515986 #1]  INFO -- : OPNsense port 0 does not match Proton forwarded port 46381. Attempt 3 of 3.
I, [2024-12-06T02:54:57.895132 #1]  INFO -- : OPNsense alias has been updated to 46381
I, [2024-12-06T02:55:02.544487 #1]  INFO -- : OPNsense alias applied successfully
I, [2024-12-06T02:55:02.544686 #1]  INFO -- : qBit check skipped
I, [2024-12-06T02:55:02.544724 #1]  INFO -- : end of loop. sleeping for 45 seconds.
I, [2024-12-06T02:55:02.544771 #1]  INFO -- : ----------

**Comment by clajiness** [comment]
Nice! That's great news. Thanks for sticking with it. If you get the chance, throw it a star. That'd be the best tip. :)

**Comment by alexjn1984** [comment]
Done!
Now I'm gonna have to look at the Plex API to see if I can get it to update there

**Comment by clajiness** [comment]
Thank you! Ohhh, that's a thought. You must be exposing Plex via Proton. I've been exposing my instance via Nginx Proxy Manager and it's worked really well. The VPN idea is interesting, though. I'll have to look into that. 👍
